#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

from os import unlink, environ

import gdrivefs.log_config

def main():
    sbin_parent = environ.get('PREFIX', '/usr/local')
    sbin_path = os.path.join(sbin_parent, 'sbin')

    for tool_name in ('gdfs', 'gdfstool', 'gdfsuninstall'):
        file_path = os.path.join(sbin_path, tool_name)

        print("Unlinking: %s" % (file_path))
        unlink(file_path)

if __name__ == '__main__':
    main()

